# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/   # tous les url sont concernés
            anonymous: ~  #

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #formulaire de login
            form_login:
                login_path: login   #chemin du formulaire
                check_path: login   #chemin pour traiter le formulaire
                csrf_token_generator: security.csrf.token_manager
            logout:
                 path: logout       #chemin pour se deconnecté
                 target: home       #une fois deconnecté redirection ds home qui est configuré dans routing.yml
            remember_me:            #cookie pour se reconnecter
                secret:   '%secret%'
                lifetime: 60    #temps de durée de vie du cookie en seconde
                path:     /           #fonctionnelle sur tous url   /admin => seulement pour admin

    providers:
        main_provider:
            entity:
                class:              SiteSupervisionBundle:User
                property:           email              #se connecter avec son username ou email ....

    encoders:
        SiteSupervisionBundle\Entity\User:     #Modifier FarmBundle
            algorithm: bcrypt       #type de cryptage
            cost: 10

    role_hierarchy:
            # ROLE_USER_COMPANY_PRINCIPAL : entreprise ayant les droits principaux de l'app (maître d'oeuvre)
            # CUSTOMER : client du ROLE_USER_COMPANY_PRINCIPAL  (maître d'ouvrage)
            # ROLE_USER_COMPANY : entreprise travaillant avec ou pour ROLE_USER_COMPANY_PRINCIPAL (artisant)
            ROLE_ADMIN: [ROLE_CUSTOMER, ROLE_USER_COMPANY_PRINCIPAL,ROLE_USER_COMPANY]
            ROLE_SUPERADMIN: ROLE_ADMIN


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_CUSTOMER, ROLE_USER_COMPANY_PRINCIPAL,ROLE_USER_COMPANY] }
        - { path: ^/administration, role: ROLE_ADMIN }
