<?php

namespace SiteSupervisionBundle\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "
            SELECT cp.id, cp.nom, cp.telephonefixe, cp.email, v.villeNom
            FROM 'SiteSupervisionBundle:Company' AS cp 
            LEFT JOIN 'SiteSupervisionBundle:VillesFranceFree' AS v WITH cp.id = v.id ");
        $query->setFirstResult(0);
        $query->setMaxResults(10);

        return $query->getResult();
    }
}
