<?php

namespace SiteSupervisionBundle\Repository;

/**
 * Construction_siteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Construction_siteRepository extends \Doctrine\ORM\EntityRepository
{
}
