<?php

namespace SiteSupervisionBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "
            SELECT c.id, c.civilite,c.nom, c.prenom, c.telephonePortable, c.telephoneFixe, c.dateNaissance, u.email, v.villeNom
            FROM 'SiteSupervisionBundle:Customer' AS c 
            LEFT JOIN 'SiteSupervisionBundle:User' AS u WITH c.id = u.id 
            LEFT JOIN 'SiteSupervisionBundle:VillesFranceFree' AS v WITH c.id = v.id ");
        $query->setFirstResult(0);
        $query->setMaxResults(10);

        return $query->getResult();

    }


}
