<?php

namespace SiteSupervisionBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $sql = "SELECT cp.id, cp.civilite,cp.nom, cp.prenom, cp.telephone_portable, cp.telephone_fixe, cp.date_naissance, u.email, v.ville_nom  
            FROM customer AS cp 
            LEFT JOIN user AS u ON cp.id = u.customer_id 
            LEFT JOIN villes_france_free AS v ON cp.villes_france_free_id = v.id";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute([]);

        return $stmt->fetchAll();

    }

    public function findSummaryBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "
            SELECT cp.*, u.email, v.villeNom, 
            FROM 'SiteSupervisionBundle:Customer' AS cp 
            LEFT JOIN 'SiteSupervisionBundle:User' AS u WITH cp.id = u.id 
            LEFT JOIN 'SiteSupervisionBundle:VillesFranceFree' AS v WITH cp.id = v.id
            LEFT JOIN 'SiteSupervisionBundle:Construction_site' AS cs WITH cp.id = cs.id 
            ");
        $query->setFirstResult(0);
        $query->setMaxResults(10);

        return $query->getResult();

    }


}
