<?php

namespace SiteSupervisionBundle\Repository;

/**
 * general_commentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class general_commentRepository extends \Doctrine\ORM\EntityRepository
{
}
