<?php

namespace SiteSupervisionBundle\Repository;

/**
 * General_commentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class General_commentRepository extends \Doctrine\ORM\EntityRepository
{
}
