<?php

namespace SiteSupervisionBundle\Repository;

/**
 * Type_constructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_constructionRepository extends \Doctrine\ORM\EntityRepository
{
}
