<?php

namespace SiteSupervisionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Type_constructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesFranceFreeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCity($idCity = null)
    {
        $qb = $this->createQueryBuilder();
        $qb
            ->addSelect('c')
            ->addSelect('i')
            ->andWhere("p.isActive = true")
            ->addOrderBy("p.dateCreated", "DESC")
            ->leftJoin("p.category", "c")
            ->leftJoin("p.images", "i");
    }
}
