<?php
/**
 * Created by PhpStorm.
 * User: cedricleblond
 * Date: 23/12/17
 * Time: 10:34
 */

namespace SiteSupervisionBundle\Command;

use SiteSupervisionBundle\Entity\User;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class AddSuperUserCommand extends ContainerAwareCommand
{
    /**
     *
     *
     * */
    public function configure()
    {
        $this
            // the name of the command (the part after "bin/console")
            ->setName('commandPerso:create-user')
            ->setDescription('Création d\'un nouveau Role super admin')
            ->addArgument('email', InputArgument::OPTIONAL, 'Insérer son E-mail :')
            ->addArgument('mdp', InputArgument::OPTIONAL, 'Insérer son mot de passe :')
            ->addArgument('role', InputArgument::OPTIONAL, 'Insérer son role [ROLE_CUSTOMER, ROLE_USER_COMPANY_PRINCIPAL,ROLE_USER_COMPANY, ROLE_ADMIN, ROLE_SUPERADMIN] :')

            // the full command description shown when running the command with
            // the "--help" option
            ->setHelp('Cette commande permet de créer un utilisateur')
        ;
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        // outputs multiple lines to the console (adding "\n" at the end of each line)
        $output->writeln([
            'Création d\'un super admin',
            '==========================',
            '',
        ]);
        $email = $input->getArgument('email');
        $mdp = $input->getArgument('mdp');
        $role = $input->getArgument('role');
        
        $user = new User();
        $user->setEmail($email);
        $user->setPassword($mdp);
        $user->setRoles($role);
        
        $this->getContainer()->get('ManagerUser')->add($user);
        
        
    }

    /**
     * @return \Symfony\Component\DependencyInjection\ContainerInterface
     */
    public function getContainer()
    {
        return parent::getContainer(); // TODO: Change the autogenerated stub
    }


}